on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: echo
        run: |
          export PATH="$PATH:/usr/local/go/bin:/home/ubuntu/go/bin"
          go
          kind
