env:
  KUBECONFIG: /root/.kube/config

on:
  push:
    branches:
      - 'feature/**'

jobs:
  ci-loadtest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: create cluster
        run: kind create cluster --config kind/cluster.yaml --name $GITHUB_JOB-$GITHUB_RUN_NUMBER
      - name: validate cluster
        run: kubectl version
      - name: clean up
        if: always()
        run: kind delete cluster --name $GITHUB_JOB-$GITHUB_RUN_NUMBER
