on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: echo
        run: |
          export PATH="$PATH:/usr/local/go/bin:/root/go/bin"
          sudo go version
          sudo kind version
          kubectl version
