on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: echo
        run: |
          echo "/usr/local/go/bin:/home/ubuntu/go/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH
          go
          kind
